### PR TITLE
Restyled buttons

### PR DESCRIPTION
**Pull request by MoweMax**
Restyled buttons to use smaller image as background and have more responsive styling.

Before:

After:

Before:

After:

### CODE REVIEW

**Comment by rybak** [comment]
Nice! Here's how it looks together with #107 and #108:

Screenshot_20210321_133955

Screenshot_20210321_134759

**Comment by rybak** [comment]
I've compared to the [Minecraft's own buttons](https://minecraft.gamepedia.com/File:Java_Edition_1.16.5.png). The bottom inset twice as wide as the bottom one:

minecraft-buttons-measures

With scaling used on that screenshot, the button's height is 40 pixels. Top inset is 2 pixels and bottom – 4 pixels.

With e7f212bff6f applied on top, it looks like this:

Screenshot_20210321_141303

**Comment by rybak** [comment]
Since mcbingo's button is 50px high, maybe it would be better to scale the insets proportionally?

`50/40*2 = 2.5` and `50/40*4 = 5`. Can't have `2.5px` border, unfortunately. Here's how `3px` and `5px` would look like:

Screenshot_20210321_143306

**Comment by rybak** [comment]
Asked in Discord, which style people prefer:

https://discord.com/channels/131720430326120449/819186365085253673/823189980662857738

**Comment by rybak** [comment]
Commit for the `3px 5px` option: 3f27019.

**Comment by rybak** [comment]
I messed up the vote (text-shadow was included in one of the screenshots by mistake), but people seem to prefer the `3px 4px` option (8ab8878).

**Comment by Joshimuz** [comment]
Can you move it to joshimuz:dev to make my life a bit easier? :D
Then I'll merge it

**Comment by rybak** [comment]
There is no my commits in this PR at the moment. I was just referencing commits in my fork.

**Comment by MoweMax** [comment]
I've updated PR to be merged into `joshimuz:dev`.

> what's happening here?
In this PR my suggestions on improvements to buttons appearance. Comparative screenshots are in the description :)

**Pull request merged**
